### ISSUE TITLE
Add list of implemented functions to the readme

### ISSUE THREAD

**Issue by aminya** [aberba/nyinaa#1]
This helps both the users and contributors. 

Something like this:

Maybe add something like this to the readme instead 
```html
# Implemented Functions
<table>
    <tr>
        <td></td>
        <td>Category</td>
        <td>Functions</td>
    </tr>
    <tr>
        <td>1</td>
        <td>Category 1</td>
        <td>function1</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Category 2</td>
        <td>function2, function3, function4</td>
    </tr>
</table>
```
which looks like this:

# Implemented Functions
<table>
    <tr>
        <td></td>
        <td>Category</td>
        <td>Functions</td>
    </tr>
    <tr>
        <td>1</td>
        <td>Category 1</td>
        <td>function1</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Category 2</td>
        <td>function2, function3, function4</td>
    </tr>
</table>

**Comment by aberba** [comment]
done
